<?php

namespace app\components\widgets\custom;

use common\sys\core\blog\BlogArticleInfoService;
use common\sys\repository\blog\models\BlogArticles;
use yii\base\Widget;

class BlogSidebarRight extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $blog_info_service  = new BlogArticleInfoService();

        $blogs = BlogArticles::find()
            ->select(['id', 'alias', 'title', 'summary'])
            ->orderBy(['rand()' => SORT_DESC])
            ->limit(3)
            ->asArray()
            ->all();

        foreach($blogs as &$item)
        {
            $item['images'] = $blog_info_service->get_blog_images($item['id']);
        }

        return $this->render(
            'blog-sidebar-right', [
                'blogs' => $blogs,
            ]
        );
    }
}