<?php

namespace app\components\widgets\custom;

use common\sys\repository\testimonials\models\Testimonials;
use yii\base\Widget;

class LandingSidebarRight extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $testimonial_rand = Testimonials::find()
            ->orderBy(['rand()' => SORT_DESC])
            ->one();

        return $this->render(
            'landing-sidebar-right', [
                'testimonial' => $testimonial_rand,
            ]
        );
    }
}