<?php

namespace app\components\widgets\request;

use app\components\AppConfig;
use yii;
use yii\base\Widget;

class FlightRequestMax extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $flight_request_max_model = new \common\sys\models\request\FlightRequestMax();

        $cabin_class = [
            AppConfig::Cabin_Class_Business => 'Business',
            AppConfig::Cabin_Class_First => 'First'
        ];

        return $this->render(
            'flight-request-max', [
                'cabin_class' => $cabin_class,
                'model' => $flight_request_max_model
            ]
        );
    }
}